theme: jekyll-theme-minimal
title: [Shane Lubold]
logo: ShaneWebsitePhoto_BW.jpeg


## News
\[5/13/20\]: Arun Chandrasekhar will be presenting our work on parameter estimation in latent space graph models at the [Workshop on Estimation of Network Processes and Information Diffusion](https://www.ideal.northwestern.edu/events/estimation-of-network-processes-and-information-diffusion/) at Northwestern!

\[4/21/20\]: I will be giving a [talk at the Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2020/onlineprogram/AbstractDetails.cfm?abstractid=313471) on parameter estimation in latent space graph models!

\[3/8/20\]: I am giving a talk on parameter estimation in latent space graph models at the [6th Annual Conference on Network Science and Economics](https://bfi.uchicago.edu/event/sixth-annual-conference-on-network-science-and-economics/#section2) at the University of Chicago. (**3/14: This conference has been cancelled.**)

\[2/20/20\]: I gave a talk to the UW undergraduate statistics club on random graphs and parameter estimation in latent space models. 

\[11/18/19\]: We submitted "Formal Definitions of Conservative PDFs."
